export const SAMPLE_ACTION = 'SAMPLE_ACTION';

export const SELECT_TOOL = 'SELECT_TOOL';
export const SELECT_TOOL_NONE = 'SELECT_TOOL_NONE';
export const SELECT_TOOL_PAN = 'SELECT_TOOL_PAN';
export const SELECT_TOOL_ZOOM_IN = 'SELECT_TOOL_ZOOM_IN';
export const SELECT_TOOL_ZOOM_OUT = 'SELECT_TOOL_ZOOM_OUT';

export const ZOOM_ON_VIEWER_CENTER = 'ZOOM_ON_VIEWER_CENTER';
export const FIT_TO_VIEWER = 'FIT_TO_VIEWER';
export const PAN_VIEWER = 'PAN_VIEWER';
export const FIT_SELECTION = 'FIT_SELECTION';
export const SET_VIEWER_VALUE = 'SET_VIEWER_VALUE';
